add better title parser
FrozenPigs/Taigabot pull request #39
Opened 2020-06-17 21:07 UTC by adedomin

Can't actually test if it works because I don't have python2. do whatever.

2020-06-18 20:16 UTC, inexist3nce commented
what is this for. what does it try to solve

2020-06-18 20:36 UTC, inexist3nce commented
i tested it and now it doesnt output anything when someone posts a link

i can't tell what's wrong, but heres stdout when posting `https://news.ycombinator.com/` in the chat

```
Traceback (most recent call last):
  File "core/reload.py", line 90, in reload
    eval(code, namespace)
  File "plugins/urls.py", line 10, in <module>
    from util.title_parse import tokenize_title_chunk, parse_title_chunk
  File "plugins/util/title_parse.py", line 56
    TitleTokenizer = re.compile(f'''(?x)
 (?P<{TitleParserTokens.WHITESPACE.name}>\\s+)
|(?P<{TitleParserTokens.TITLE.name}>[<][/]?\\s*[tT][iI][tT][lL][eE][^>]*[>])
|(?P<{TitleParserTokens.WORDS.name}>[^<>&"'\\s]+)
|(?P<{TitleParserTokens.DEC_CHAR_ENT.name}>
  [&][#]
   (?P<__internal_dec_code_value>\\d+)
  ;
 )
|(?P<{TitleParserTokens.HEX_CHAR_ENT.name}>
  [&][#]x
   (?P<__internal_hex_code_value>[a-fA-F0-9]+)
  ;
 )
|(?P<{TitleParserTokens.WORD_CHAR_ENT.name}>
  [&]
   (?P<__internal_word_code_value>\\w+;)
 )
|(?P<{TitleParserTokens.OTHER_TAG.name}>
  [<][/]?\\s*
   (?P<__internal_tag_name>[\\w!]+)
  [^>]*[>])
|(?P<{TitleParserTokens.INVALID.name}>.)
''')

  ^
SyntaxError: invalid syntax
```

2020-06-18 22:00 UTC, adedomin commented
ok I fixed it for python2

2020-06-20 22:28 UTC, inexist3nce commented on plugins/util/title_parse.py
> +char_entities = {
i dont like this

2020-06-20 23:21 UTC, inexist3nce commented
i dont like the 2358 lines, but hey it solves the issue. the bold/underline/italic support is nice, too.

up to u @FrozenPigs

2020-06-20 23:21 UTC, ineeee approved these changes
wtf do i put on this small comment box

edit: oh lol

2020-06-21 01:21 UTC, ineeee requested changes
i can't accept a bump from 3.3 to 4.5 without extensive testing. lxml is used *everywhere*

2020-06-21 23:58 UTC, adedomin commented
it's more work than I feared, bot just keeps getting more problematic the more I probe it. outputs broken extended-ascii or some latin-1 encoding anyhow unless controlling pty is sufficient enough for the python interpreter. not sure how this affects a literal socket, but it seems to. python2 is just too broken and this is more pissing me off than it's worth.

2020-06-21 23:58 UTC, closed without merging